<?php
$databaseLink = "..".DS."app".DS."data".DS."databaseBackups";
?>
<br><br><br><br>
<div class="page-header"><h1>YOU HAVE SUCCESSFULLY BACKED UP THE DATABASE!</h1></div>
<br><br><br>

<div class="container"><a href="?page=home">Click here to return home</a></div>
<br>    <br><br>

<div class="container"><a href="<?php echo $databaseLink?>">Click here to see databases</a></div>
<br><br>