<br><br><br>
<div class="container"><a href="?page=users&action=add" id="createAccount">Create an account</a></div>

<br><br>


<div class="container"><h3 class="header3">Accounting Firm Notification System</h3></div>

<div class="container">
    <div class = "row">
        <div class="col-4 offset-md-4 form-div">
                <br>
                <form action="?page=users&action=logIn" method="post">
                    <label for="usernameField">Username</label>
                    <input required type="text" name="username" class="form-control" id="usernameField" value="w9181089">
                    <label for="passwordField">Password</label>
                    <input type="password" name="password" class="form-control" id="passwordField" value="Vacation2">
                    <input required type="hidden" name="id">
                    <br>
                    <input type="submit" value="Log in">
                </form>
        </div>
    </div>
</div>