<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>
<br><br>
<br><br><br><br><br><br><br><br><br><br>

<a href="?page=home">You have successfully Backed up the Database: Click here to return home</a>
<a href="?page=home">You have successfully Backed up the Database: Click here to return home</a>


<div><h1>You have Successfully Restored the Database</h1></div>

<div class="container"><h1>YOU HAVE SUCCESSFULLY RESTORED THE DATABASE</h1></div>

<div class="page-header"><h1>You have Successfully Restored the Database</h1></div>
