<!-- this is the view for activating or archiving a client-->
<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<?php
require_once '../app/model/clients.php';

?>
<br><br><br><br>
<h1>Archive/Activate Clients</h1>
<br>

<div class="container">
    <form action="./?page=clients&action=search" method="post">
        Search Clients: <input type="text" name="input">
        <input type="submit" value="Submit">
    </form>
</div>

<div class="container table-responsive" >
    <table class="table table-dark table-hover">
        <tr>
            <th>Client ID</th>
            <th>Company Name</th>
            <th>Business Number</th>
            <th>Contact's First Name</th>
            <th>Contact's Last Name</th>
            <th>Phone Number</th>
            <th>Cell Number</th>
            <th>Website</th>
            <th>Status</th>

        </tr>
        <?php
        foreach ($clients as $key=>$client){
            ?>
            <tr>
                <td><?php echo $client->getId(); ?></td>
                <td><?php echo $client->getCompanyName(); ?></td>
                <td><?php echo $client->getBusinessNumber(); ?></td>
                <td><?php echo $client->getFirstName(); ?></td>
                <td><?php echo $client->getLastName(); ?></td>
                <td><?php echo $client->getPhoneNumber(); ?></td>
                <td><?php echo $client->getCellNumber(); ?></td>
                <td><?php echo $client->getWebsite(); ?></td>
                <td><?php echo $client->getStatus(); ?></td>
                <td><a href="?page=clients&action=activate&id=<?php echo $client->getId(); ?>">Activate</a></td>
                <td><a href="?page=clients&action=archive&id=<?php echo $client->getId(); ?>">Archive</a></td>
            </tr>
            <?php
        }
        ?>
    </table>
</div>
<br>
<br>
<a class = "addSomething" href="?page=clients&action=add">Add a Client</a>