<!-- this is a form that asks for fields to edit, while also passing values through hidden fields-->
<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<?php
require_once '../app/model/Client.php';
?>
<br><br><br>
<div class="container"><h3 class="header3">Change a Client in the Notification System (* is Required)</h3></div>

<div class="container">
    <div class = "row">
        <div class="col-4 offset-md-4 form-div">
            <form action="./?page=clients&action=doEdit" method="post">
                <div class="input-group">
                    Client ID: <?php echo $client->getId();?>
                </div>
                <br>
                <div class="input-group">
                    <label for="companyName">Company Name:*</label>
                    <input required type="text" name="companyName" id="companyName" value="<?php echo $client->getCompanyName();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="businessNum">Business Number:*</label>
                    <input required type="text" name="businessNum" id="businessNum" value="<?php echo $client->getBusinessNumber();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="firstName">First Name:*</label>
                    <input required type="text" name="firstName"  id="firstName" value="<?php echo $client->getFirstName();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="lastName">Last Name:*</label>
                    <input required type="text" name="lastName" id="lastName" value="<?php echo $client->getLastName();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="phoneNum">Phone Number:*</label>
                    <input required type="text" name="phoneNum" id="phoneNum" value="<?php echo $client->getPhoneNumber();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="phoneNum">Cell Number:*</label>
                    <input required type="text" name="cellNum" value="<?php echo $client->getCellNumber();?>">
                </div>
                <br>

                <div class="input-group">
                    <label for="website">Website:</label>
                    <input type="text" name="website" id="website" value="<?php echo $client->getWebsite();?>">
                </div>
                <br>

                <div class="input-group">
                    Status: <?php echo $client->getStatus();?>
                </div>
                <br>
                <input type="hidden" name="status" value="<?php echo $client->getStatus();?>">
                <input type="hidden" name="id" value="<?php echo $client->getId();?>">
                <input type="submit" value="Submit">

            </form>
        </div>
    </div>
</div>




