<!-- this is the view to enable or disable a notification -->
<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<?php
require_once '../app/model/notifications.php';

?>
<br><br><br><br>
<h1>View Notifications</h1>
<br>


<div class="container">
    <form action="./?page=notifications&action=searchNotification" method="post">
        Search Notifications: <input type="text" name="input">
        <input type="submit" value="Submit">
    </form>
</div>

<div class="container table-responsive" >
    <table class="table table-dark table-hover">
        <tr>
            <th>Notification ID</th>
            <th>Notification Name</th>
            <th>Type</th>
            <th>Status</th>


        </tr>
        <?php
        foreach ($notifications as $key=>$notification){
            ?>
            <tr>
                <td><?php echo $notification->getId(); ?></td>
                <td><?php echo $notification->getName(); ?></td>
                <td><?php echo $notification->getType(); ?></td>
                <td><?php echo $notification->getStatus(); ?></td>
                <td><a href="?page=notifications&action=enableNotification&id=<?php echo $notification->getId(); ?>">Enable</a></td>
                <td><a href="?page=notifications&action=disableNotification&id=<?php echo $notification->getId(); ?>">Disable</a></td>
            </tr>
            <?php
        }
        ?>
    </table>
</div>
<br>
<br>
<a class = "addSomething" href="?page=notifications&action=addNotification">Add a Notification</a>