<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<?php
require_once '../app/model/notifications.php';
$input = get('input');
$notifications = searchNotification($conn , $input);
?>
<br><br><br><br>
<h1>List of Searched Notifications</h1>
<br>

<div class="container table-responsive" >
    <table class="table table-dark table-hover">
        <tr>
            <th>Notification ID</th>
            <th>Notification Name</th>
            <th>Type</th>
            <th>Status</th>
        </tr>
        <?php
        foreach ($notifications as $key=>$notification){
            ?>
            <tr>
                <td><?php echo $notification->getId(); ?></td>
                <td><?php echo $notification->getName(); ?></td>
                <td><?php echo $notification->getType(); ?></td>
                <td><?php echo $notification->getStatus(); ?></td>
                <td><a href="?page=notifications&action=editNotification&id=<?php echo $notification->getId(); ?>">Edit</a></td>
                <td><a href="?page=notifications&action=enableNotification&id=<?php echo $notification->getId(); ?>">Enable</a></td>
                <td><a href="?page=notifications&action=disableNotification&id=<?php echo $notification->getId(); ?>">Disable</a></td>
            </tr>
            <?php
        }
        ?>
    </table>
</div>
<br>
<br>
<a class = "addSomething" href="?page=notifications&action=addNotification">Add a Notification</a>