<!--this is the ordinary view for seeing the clients,
no other functions, other than an adding link at the bottom -->
<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<br><br><br><br>
<div class="page-header"><h1>View Logs</h1></div>
<!-- maybe I will do a search for logs-->
<!--<form action="./?page=clients&action=search" method="post"><br>
    Search Clients: <input type="text" name="input"> <br><br>
    <input type="submit" value="Submit">
</form> -->
<div class="container table-responsive" >
    <table class="table table-dark table-hover">
        <tr>
            <th>Log ID</th>
            <th>Username</th>
            <th>Module</th>
            <th>Action</th>
            <th>Date/Time</th>
            <th>Ip Address</th>
        </tr>

        <?php
        foreach ($logs as $key=>$log){
        ?>
            <tr>
                <td><?php echo $log->getId(); ?></td>
                <td><?php echo $log->getUsername(); ?></td>
                <td><?php echo $log->getModuleName(); ?></td>
                <td><?php echo $log->getActionDone(); ?></td>
                <td><?php echo $log->getDateTime(); ?></td>
                <td><?php echo $log->getIpAddress(); ?></td>
            </tr>
        <?php
    }
    ?>
</table>
