<!-- This is the form for adding a client notification, the $highestID variable gives the next id in the list-->
<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>
<br><br><br><br>
<div class="page-header"><h3>Change Client Event in System (* is Required)</h3></div>

<div class="container">
    <div class = "row">
        <div class="col-4 offset-md-4 form-div">
            <form action="./?page=clientNotifications&action=doAddClientNotification" method="post">
                <div class="input-group">
                    <label for="clientID">Client ID:* </label>
                    <input type="text" name="clientID" id="clientID">
                </div>

                <br><br>


                <div class="input-group">
                    <label for="notificationID">Notification ID:* </label>
                    <input type="text" name="notificationID" id="notificationID">
                </div>

                <br><br>


                <div class="input-group">
                    <label for="startDate">Start Date/Time:* </label>
                    <input type="text" name="startDate" id="startDate">
                </div>

                <br><br>

                <div class="input-group">
                    <label for="frequency">Frequency: </label>
                    <input type="text" name="frequency" id="frequency">
                </div>

                <br><br>

                <div class="input-group">
                    <p>Status: active</p>
                </div>

                <br>
                <input type="hidden" name="status" value="active"><br><br>
                <input type="hidden" name="id">
                <input type="submit" value="Save">
            </form>
        </div>
    </div>
</div>
