<?php if($_SESSION['username'] == null || $_SESSION['password']== null){
    $page = 'logIn';
}?>

<?php
require_once '../app/model/users.php';
$input = get('input');
$users = searchUser($conn , $input);

?>
<br><br><br><br>
<h1>List of Searched Users</h1>
<br>
<br>
<div class="container table-responsive" >
    <table class="table table-dark table-hover">
    <tr>
        <th>User ID</th>
        <th>User First Name</th>
        <th>User Last Name</th>
        <th>User Email</th>
        <th>User Cell Number</th>
        <th>User Position</th>
        <th>Username</th>
        <th>Password</th>
        <th>User Status</th>
        <th>User Picture</th>

    </tr>
    <?php
    foreach ($users as $key=>$user){
        ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getUserFirstName(); ?></td>
            <td><?php echo $user->getUserLastName(); ?></td>
            <td><?php echo $user->getUserEmail(); ?></td>
            <td><?php echo $user->getUserCellNumber(); ?></td>
            <td><?php echo $user->getUserPosition(); ?></td>
            <td><?php echo $user->getUsername(); ?></td>
            <td><?php echo $user->getPassword(); ?></td>
            <td><?php echo $user->getStatus(); ?></td>
            <td><?php echo $user->getUserPic(); ?></td>
            <td><a href="?page=users&action=update&id=<?php echo $user->getId(); ?>">Edit</a></td>
            <td><a href="?page=users&action=activate&id=<?php echo $user->getId(); ?>">Activate</a></td>
            <td><a href="?page=users&action=suspend&id=<?php echo $user->getId(); ?>">Archive</a></td>
        </tr>
        <?php
    }
    ?>
    </table>
</div>
<br>
<br>
<a class = "addSomething" href="?page=users&action=add">Add a User</a>